# Generated by Django 3.1.1 on 2020-10-22 20:45

import Base_Clase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_Clase', models.IntegerField(default=Base_Clase.models.random_string)),
                ('NombreClas', models.CharField(max_length=50)),
                ('ClassInicio', models.TimeField(verbose_name='%H:%M')),
                ('ClassTermino', models.TimeField(verbose_name='%H:%M')),
                ('Profesor', models.CharField(max_length=50)),
                ('AsistHombres', models.IntegerField()),
                ('AsistMujeres', models.IntegerField()),
                ('AsistTotales', models.IntegerField()),
                ('AsistPorcentaje', models.IntegerField()),
                ('PaseVencidos', models.IntegerField()),
            ],
        ),
    ]
