# Generated by Django 3.1.1 on 2020-09-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Clase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klase',
            old_name='AsitPorcentaje',
            new_name='AsistPorcentaje',
        ),
    ]
