# Generated by Django 3.1.1 on 2020-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Clase', '0002_auto_20200920_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='klase',
            name='ClassInicio',
            field=models.TimeField(default='00:00', verbose_name='%H:%M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klase',
            name='ClassTermino',
            field=models.TimeField(default='00:00', verbose_name='%H:%M'),
            preserve_default=False,
        ),
    ]
