# Generated by Django 3.1.1 on 2020-09-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Global', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadomensual',
            name='AsistProvidencia',
        ),
        migrations.RemoveField(
            model_name='estadomensual',
            name='IngresosProvidencia',
        ),
        migrations.RemoveField(
            model_name='estadomensual',
            name='NuevosProvidencia',
        ),
    ]
