# Generated by Django 3.1.1 on 2020-11-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=13, unique=True)),
                ('Nombre', models.CharField(max_length=30)),
                ('Genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=6)),
                ('Nacimiento', models.DateField()),
                ('Profesion', models.CharField(max_length=50)),
                ('DirPersonal', models.CharField(max_length=50)),
                ('DirLaboral', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Ntelefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagosAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Alumno', models.IntegerField()),
                ('RUT', models.CharField(max_length=13)),
                ('Nombre', models.CharField(max_length=30)),
                ('Local', models.CharField(choices=[('Casa Matriz', 'Casa Matriz'), ('Bellavista', 'Bellavista'), ('Providencia', 'Providencia'), ('La Florida', 'La Florida')], max_length=30)),
                ('ClasePagada', models.CharField(max_length=30)),
                ('Num_Clases_Pagadas', models.PositiveIntegerField()),
                ('Mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octube'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=15)),
                ('Anno', models.PositiveIntegerField()),
                ('IngresoAlumno', models.PositiveIntegerField()),
                ('MetodoPago', models.CharField(max_length=30)),
                ('Grupal', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Clase_Perteneciente', models.CharField(max_length=30)),
                ('Code_Clase', models.IntegerField()),
                ('Local', models.CharField(choices=[('Casa Matriz', 'Casa Matriz'), ('Bellavista', 'Bellavista'), ('Providencia', 'Providencia'), ('La Florida', 'La Florida')], max_length=30)),
                ('Dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10)),
                ('Horario_Inicio', models.TimeField(verbose_name='%H:%M')),
                ('Horario_Termino', models.TimeField(verbose_name='%H:%M')),
                ('AsistTotales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventInscrito', models.CharField(max_length=30)),
                ('ID_Event', models.IntegerField()),
                ('NombreParticipante', models.CharField(max_length=30)),
                ('Escena', models.CharField(max_length=30)),
            ],
        ),
    ]
