# Generated by Django 3.1.1 on 2020-10-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Alumno', '0002_participantesevent_id_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosalumno',
            name='Horario_Inicio',
            field=models.TimeField(default='00:00', verbose_name='%H:%M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagosalumno',
            name='Horario_Termino',
            field=models.TimeField(default='00:00', verbose_name='%H:%M'),
            preserve_default=False,
        ),
    ]
