# Generated by Django 3.1.1 on 2020-11-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreClas', models.CharField(max_length=50)),
                ('Local', models.CharField(choices=[('Casa Matriz', 'Casa Matriz'), ('Bellavista', 'Bellavista'), ('Providencia', 'Providencia'), ('La Florida', 'La Florida')], max_length=30)),
                ('Dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10)),
                ('ClassInicio', models.TimeField(verbose_name='%H:%M')),
                ('ClassTermino', models.TimeField(verbose_name='%H:%M')),
                ('Profesor', models.CharField(max_length=50)),
                ('AsistHombres', models.PositiveIntegerField(default=0)),
                ('AsistMujeres', models.PositiveIntegerField(default=0)),
                ('AsistTotales', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
