# Generated by Django 3.1.1 on 2020-10-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klase',
            name='Local',
            field=models.CharField(default='Ninguno', max_length=30),
            preserve_default=False,
        ),
    ]
