# Generated by Django 3.1.1 on 2020-10-22 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=13)),
                ('Nombre', models.CharField(max_length=30)),
                ('Genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=6)),
                ('Nacimiento', models.DateField()),
                ('Profesion', models.CharField(max_length=50)),
                ('DirPersonal', models.CharField(max_length=50)),
                ('DirLaboral', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Ntelefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagosAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=13)),
                ('Nombre', models.CharField(max_length=30)),
                ('FechaIngresos', models.DateField(default=datetime.date.today)),
                ('Local', models.CharField(max_length=30)),
                ('ClasePagada', models.CharField(max_length=30)),
                ('IngresoAlumnno', models.IntegerField()),
                ('MetodoPago', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Clase_Perteneciente', models.CharField(max_length=30)),
                ('Local', models.CharField(max_length=30)),
                ('Code_Clase', models.IntegerField()),
                ('Horario_Inicio', models.TimeField(verbose_name='%H:%M')),
                ('Horario_Termino', models.TimeField(verbose_name='%H:%M')),
                ('AsistPorcentaje', models.IntegerField()),
                ('AsistTotales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventInscrito', models.CharField(max_length=30)),
                ('NombreParticipante', models.CharField(max_length=30)),
                ('Escena', models.CharField(max_length=30)),
            ],
        ),
    ]
