# Generated by Django 3.1.1 on 2020-09-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=13)),
                ('Nombre', models.CharField(max_length=30)),
                ('Nacimiento', models.DateField()),
                ('Profesion', models.CharField(max_length=50)),
                ('DirPersonal', models.CharField(max_length=50)),
                ('DirLaboral', models.CharField(max_length=50)),
                ('Asistencias', models.IntegerField()),
            ],
        ),
    ]
