# Generated by Django 3.1.1 on 2020-09-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Alumno', '0002_auto_20200918_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Genero',
            field=models.CharField(default='Hombre', max_length=6),
            preserve_default=False,
        ),
    ]
