# Generated by Django 3.0.6 on 2020-10-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Alumno', '0003_alumno_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosAlumno',
            fields=[
                ('alumno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Base_Alumno.Alumno')),
                ('FechaIngresos', models.DateField()),
                ('ClasePagada', models.CharField(max_length=30)),
                ('IngresoAlumnno', models.IntegerField()),
                ('MetodoPago', models.CharField(max_length=30)),
            ],
            bases=('Base_Alumno.alumno',),
        ),
    ]
