# Generated by Django 3.1.1 on 2020-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEvent', models.CharField(max_length=30)),
                ('FechaEvent', models.DateField()),
                ('EventInicio', models.TimeField(verbose_name='%H:%M')),
                ('EventTermino', models.TimeField(verbose_name='%H:%M')),
                ('LocalAdmin', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
